export const ACTION_START = "ACTION_START";
export const ACTION_FAILED = "ACTION_FAILED";
export const ACTION_SUCCESS = "ACTION_SUCCESS";
export const ACTION_CLEAR = "ACTION_CLEAR";

export const SELECT_CONTACT_SUCCESS = "SELECT_CONTACT_SUCCESS";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const SEARCH_CONTACTS_SUCCESS = "SEARCH_CONTACTS_SUCCESS";
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS";
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
export const CLEAR_CONTACT_SUCCESS_MSG = "CLEAR_CONTACT_SUCCESS_MSG";
